# Generated by Django 2.2.24 on 2024-01-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20240109_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='ФИО владельца'),
        ),
    ]
