# Generated by Django 2.2.24 on 2024-01-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20240110_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owner', to='property.Flat', verbose_name='Квартиры'),
        ),
    ]
