# Generated by Django 2.2.24 on 2024-01-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20240111_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint',
            new_name='text',
        ),
    ]
